### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by cloudcat214** [ermaozi/get_subscribe#35]
![image](https://user-images.githubusercontent.com/99686044/174198508-c1d721c5-5b73-4d67-8497-b7482b15a29d.png)
首先，非常感谢你制作的订阅，非常好用，只是有一个小问题会导致无法正常使用。

就是订阅里面的节点名称有很多相同的，会导致订阅无法使用，clash老提示错误，不能使用。

需要手动修改“name”后才能使用，“name”必须是唯一的。

希望后续能够改进。

节点很不错，非常感谢。

**Comment by ermaozi** [comment]
现在的节点应该已经没有上述问题了
