### ISSUE TITLE
到底是12小时一更还是6小时一更

### ISSUE THREAD

**Issue by suno2015** [ermaozi/get_subscribe#37]
在 description 中写的是 12 小时一更，在 readme 中写的是 6 小时一更

到底哪一个是正确的，烦请将两个地方所写的更新频率改为一致 🙏

**Comment by Zzhuanping** [comment]
我是在电脑上使用v2ray，在更新订阅的时候轮到楼主提供的短链接为啥总是订阅失败呢
复制的订阅是这个https://git.io/emzv2ray
ps：别的机场地址能够正常使用

**Comment by sunhuixiang** [comment]
> 我是在电脑上使用v2ray，在更新订阅的时候轮到楼主提供的短链接为啥总是订阅失败呢
> 复制的订阅是这个https://git.io/emzv2ray
> ps：别的机场地址能够正常使用

用长链接试试

**Comment by Zzhuanping** [comment]
> 短链接直接不行，更新订阅的时候会提示检查链接

**Comment by Zzhuanping** [comment]
> > 我是在电脑上使用v2ray，在更新订阅的时候轮到楼主提供的短链接为啥总是订阅失败呢
> > 复制的订阅是这个https://git.io/emzv2ray
> > ps：别的机场地址能够正常使用
> 
> 用长链接试试

短链接直接不行，更新订阅的时候会提示检查链接

**Comment by ermaozi** [comment]
12小时一更，刚改好了

**Comment by Zzhuanping** [comment]
这个地址是不能在V2ray上用吗，我用V2ray他死活解析不出来啊
